"""Add is_fallback_geo to detected_events

Revision ID: 973d066a7771
Revises: adb3744b0ec5
Create Date: 2026-09-02 23:30:00.000000

Hand-written (not autogenerated): the existing baseline migration was
autogenerated against a DB that also has PostGIS TIGER geocoder tables
loaded, which drags a large unrelated diff into any --autogenerate run
in this environment. A single boolean column is simpler to write by hand
than to filter that noise out of an autogenerate diff.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '973d066a7771'
down_revision: Union[str, None] = 'adb3744b0ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'detected_events',
        sa.Column('is_fallback_geo', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    op.drop_column('detected_events', 'is_fallback_geo')
