from aiogram.utils.keyboard import ReplyKeyboardBuilder, InlineKeyboardBuilder

def get_main_keyboard():
    builder = ReplyKeyboardBuilder()
    builder.button(text="🟢 ВІДБІЙ МОНІТОРИНГ")
    builder.button(text="🔄 АКТУАЛІЗАЦІЯ ПОДІЙ")
    builder.button(text="🛸 Радар Контур")
    builder.button(text="🔥 Супутник NASA")
    builder.button(text="🎖 Ключові інциденти")
    builder.button(text="💥 Резонанс")
    builder.button(text="📊 Аналітика")
    builder.button(text="📋 Звіт (12 год)")
    builder.button(text="🎯 Прогноз загроз")
    builder.button(text="🌐 Веб-мапа")
    builder.button(text="🔍 Глибокий OSINT")
    builder.button(text="📡 Статус системи")
    builder.button(text="📈 Графік активності")
    builder.button(text="📊 Експорт CSV")
    builder.button(text="🔑 Мій ключ")
    builder.button(text="🐾 ТУПО МЯВ")
    builder.adjust(2, 2, 2, 2, 2, 2, 3, 1)
    return builder.as_markup(resize_keyboard=True)
